[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#1f77b4"
backgroundColor="#f8f9fa"
secondaryBackgroundColor="#e0e0e0"
textColor="#262730"

[client]
toolbarMode = "minimal"
